"""initial_schema

Revision ID: 00fbf724d9ea
Revises: 
Create Date: 2026-06-08 19:21:04.716408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00fbf724d9ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_banlists_format_effective_date', 'banlists', ['format', 'effective_date'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_card_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('frame_type', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('attribute', sa.String(length=50), nullable=True),
    sa.Column('archetype', sa.String(length=255), nullable=True),
    sa.Column('level_rank_link', sa.Integer(), nullable=True),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('def', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('linkval', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pend_description', sa.Text(), nullable=True),
    sa.Column('monster_description', sa.Text(), nullable=True),
    sa.Column('tcg_date', sa.DateTime(), nullable=True),
    sa.Column('ocg_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_card_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_cards_archetype', 'cards', ['archetype'], unique=False)
    op.create_index('ix_cards_external_card_id', 'cards', ['external_card_id'], unique=False)
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('archetype_label', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('ydk_import', 'manual', 'scraped', 'api_import', name='decksourcetype'), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decks_archetype_label', 'decks', ['archetype_label'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('cards', 'banlist', 'images', 'analytics', name='synctype'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournaments_event_date', 'tournaments', ['event_date'], unique=False)
    op.create_table('banlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banlist_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('forbidden', 'limited', 'semi_limited', 'unlimited', name='banliststatus'), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banlist_id'], ['banlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_banlist_entries_banlist_id_card_id', 'banlist_entries', ['banlist_id', 'card_id'], unique=False)
    op.create_table('card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('image_kind', sa.String(length=50), nullable=False),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('missing', 'queued', 'ready', 'failed', name='imagestatus'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_card_images_card_id_status', 'card_images', ['card_id', 'status'], unique=False)
    op.create_table('deck_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('banlist_id', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banlist_id'], ['banlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deck_submissions_deck_id', 'deck_submissions', ['deck_id'], unique=False)
    op.create_index('ix_deck_submissions_format_event_date', 'deck_submissions', ['format', 'event_date'], unique=False)
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_submission_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('main', 'extra', 'side', name='cardsection'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deck_submission_id'], ['deck_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deck_cards_deck_submission_id', 'deck_cards', ['deck_submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deck_cards_deck_submission_id', table_name='deck_cards')
    op.drop_table('deck_cards')
    op.drop_index('ix_deck_submissions_format_event_date', table_name='deck_submissions')
    op.drop_index('ix_deck_submissions_deck_id', table_name='deck_submissions')
    op.drop_table('deck_submissions')
    op.drop_index('ix_card_images_card_id_status', table_name='card_images')
    op.drop_table('card_images')
    op.drop_index('ix_banlist_entries_banlist_id_card_id', table_name='banlist_entries')
    op.drop_table('banlist_entries')
    op.drop_index('ix_tournaments_event_date', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_table('sync_runs')
    op.drop_table('players')
    op.drop_index('ix_decks_archetype_label', table_name='decks')
    op.drop_table('decks')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_index('ix_cards_external_card_id', table_name='cards')
    op.drop_index('ix_cards_archetype', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_banlists_format_effective_date', table_name='banlists')
    op.drop_table('banlists')
    # ### end Alembic commands ###
