"""add_unique_card_images_card_kind

Revision ID: 80311f74b4a2
Revises: 00fbf724d9ea
Create Date: 2026-06-08 20:30:52.023748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80311f74b4a2'
down_revision: Union[str, None] = '00fbf724d9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_card_images_card_kind', 'card_images', ['card_id', 'image_kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_card_images_card_kind', 'card_images', type_='unique')
    # ### end Alembic commands ###
